import type { HttpMethod } from "@/lib/blocklog";

export type ApiEndpointDefinition = {
  category: string;
  label: string;
  method: HttpMethod;
  path: string;
  description: string;
  pageHref?: string;
  liveOnly?: boolean;
  samplePayload?: string;
};

export const apiCatalog: ApiEndpointDefinition[] = [
  {
    category: "Health",
    label: "Health Check",
    method: "GET",
    path: "/health",
    description: "Return current API service health.",
    pageHref: "/dashboard/monitoring/integrity",
  },
  {
    category: "Health",
    label: "Liveness Probe",
    method: "GET",
    path: "/health/live",
    description: "Fast liveness probe for runtime and deployment health checks.",
    pageHref: "/docs/operations",
  },
  {
    category: "Health",
    label: "Readiness Probe",
    method: "GET",
    path: "/health/ready",
    description: "Readiness probe for dependency-aware startup and rollout checks.",
    pageHref: "/docs/operations",
  },
  {
    category: "Observability",
    label: "Metrics",
    method: "GET",
    path: "/metrics",
    description: "Return aggregate request and ingestion metric series.",
    pageHref: "/dashboard/system/pipeline",
  },
  {
    category: "Authentication",
    label: "Login",
    method: "POST",
    path: "/auth/login",
    description: "Exchange credentials for an access token and company scope.",
    samplePayload:
      '{\n  "email": "you@company.com",\n  "password": "super-secure-password"\n}',
  },
  {
    category: "Authentication",
    label: "Signup",
    method: "POST",
    path: "/auth/signup",
    description: "Create a user account and optionally bootstrap the first company during signup.",
    samplePayload:
      '{\n  "username": "founder",\n  "email": "you@company.com",\n  "password": "super-secure-password",\n  "company_id": "cmp_84f02",\n  "company_name": "Acme Financial"\n}',
  },
  {
    category: "Authentication",
    label: "Forgot Password",
    method: "POST",
    path: "/auth/forgot-password",
    description: "Generate a password reset token for an existing user.",
    pageHref: "/auth/forgot-password",
    samplePayload: '{\n  "email": "you@company.com"\n}',
  },
  {
    category: "Authentication",
    label: "Reset Password",
    method: "POST",
    path: "/auth/reset-password",
    description: "Validate a reset token and update the user password.",
    pageHref: "/auth/reset-password",
    samplePayload:
      '{\n  "token": "paste-reset-token",\n  "password": "new-super-secure-password"\n}',
  },
  {
    category: "Authentication",
    label: "Current User",
    method: "GET",
    path: "/auth/me",
    description: "Return the authenticated user profile and company association.",
    pageHref: "/dashboard/settings",
  },
  {
    category: "Authentication",
    label: "List API Keys",
    method: "GET",
    path: "/auth/api_keys",
    description: "List the single-company integration key inventory.",
    pageHref: "/dashboard/api-keys",
  },
  {
    category: "Authentication",
    label: "Create API Key",
    method: "POST",
    path: "/auth/api_keys",
    description: "Create one active integration API key for the current company.",
    pageHref: "/dashboard/api-keys",
    samplePayload:
      '{\n  "name": "Production API",\n  "rate_limit_per_minute": 1000\n}',
  },
  {
    category: "Authentication",
    label: "Revoke API Key",
    method: "DELETE",
    path: "/auth/api_keys/{key_id}",
    description: "Revoke a specific API key by its identifier.",
    pageHref: "/dashboard/api-keys",
  },
  {
    category: "Companies",
    label: "Register Company",
    method: "POST",
    path: "/companies",
    description: "Provision a company or project namespace for new workloads from an authenticated admin surface.",
    samplePayload:
      '{\n  "company_id": "cmp_84f02",\n  "company_name": "Acme Financial"\n}',
  },
  {
    category: "Companies",
    label: "List Companies",
    method: "GET",
    path: "/companies",
    description: "List companies for the authenticated admin portal.",
    pageHref: "/admin",
  },
  {
    category: "Companies",
    label: "Get Company",
    method: "GET",
    path: "/companies/{company_id}",
    description: "Load tenant metadata, region, and account status.",
    pageHref: "/dashboard/settings",
  },
  {
    category: "Policy",
    label: "Retention Policy",
    method: "GET",
    path: "/policy/retention",
    description: "Read the active retention policy for the current company.",
    pageHref: "/dashboard/settings",
  },
  {
    category: "Usage",
    label: "Usage",
    method: "GET",
    path: "/usage",
    description: "Return ingestion and verification usage totals.",
    pageHref: "/dashboard",
  },
  {
    category: "Integrity",
    label: "Integrity Status",
    method: "GET",
    path: "/integrity/status",
    description: "Return current chain and verification health indicators.",
    pageHref: "/dashboard/monitoring/integrity",
  },
  {
    category: "Integrity",
    label: "Integrity Report",
    method: "GET",
    path: "/integrity/report",
    description: "Return deeper continuity diagnostics and recent batch issues.",
    pageHref: "/dashboard/monitoring/integrity",
  },
  {
    category: "Public Verification",
    label: "Public Verify",
    method: "GET",
    path: "/public/verify/{proof_id}",
    description: "Verify a proof reference without an authenticated session.",
    pageHref: "/dashboard/verify",
  },
  {
    category: "Admin",
    label: "Admin Overview",
    method: "GET",
    path: "/admin/overview",
    description: "Return environment-wide counts, anchored-batch totals, and recent admin actions.",
    pageHref: "/admin",
  },
  {
    category: "Admin",
    label: "Admin Companies",
    method: "GET",
    path: "/admin/companies",
    description: "Return the detailed tenant list used by the admin portal.",
    pageHref: "/admin",
  },
  {
    category: "Admin",
    label: "Tenant API Keys",
    method: "GET",
    path: "/admin/companies/{company_id}/api-keys",
    description: "Inspect integration keys for a specific tenant from the admin portal.",
    pageHref: "/admin",
  },
  {
    category: "Admin",
    label: "Update Tenant Controls",
    method: "PATCH",
    path: "/admin/companies/{company_id}/controls",
    description: "Update monthly limit overrides, pilot status, refund state, notes, and company status.",
    pageHref: "/admin",
    samplePayload:
      '{\n  "monthly_event_limit": 5000000,\n  "pilot_status": "active",\n  "refund_status": "not_requested",\n  "status": "ACTIVE"\n}',
  },
  {
    category: "Admin",
    label: "Kill Switch",
    method: "POST",
    path: "/admin/companies/{company_id}/kill-switch",
    description: "Suspend a tenant and revoke all active API keys.",
    pageHref: "/admin",
    samplePayload:
      '{\n  "reason": "Abuse detected",\n  "revoke_api_keys": true,\n  "suspend_company": true\n}',
  },
  {
    category: "Logs",
    label: "Create Log",
    method: "POST",
    path: "/logs",
    description: "Ingest a single event into the sealed audit trail.",
    pageHref: "/dashboard/logs",
    samplePayload:
      '{\n  "event_type": "payment.created",\n  "source": "payments-api",\n  "idempotency_key": "evt_payment_123_created",\n  "data": {\n    "user_id": "123",\n    "amount": 2000,\n    "currency": "USD"\n  }\n}',
  },
  {
    category: "Logs",
    label: "Ingest Logs Batch",
    method: "POST",
    path: "/logs/batch",
    description: "Ingest a batch of logs into the audit pipeline.",
    pageHref: "/dashboard/system/pipeline",
    samplePayload:
      '{\n  "logs": [\n    {\n      "event_type": "payment.created",\n      "source": "payments-api",\n      "idempotency_key": "evt_payment_123_created",\n      "data": {\n        "user_id": "123",\n        "amount": 2000,\n        "currency": "USD"\n      }\n    },\n    {\n      "event_type": "payment.updated",\n      "source": "payments-api",\n      "idempotency_key": "evt_payment_123_updated",\n      "data": {\n        "user_id": "123",\n        "status": "captured"\n      }\n    }\n  ]\n}',
  },
  {
    category: "Logs",
    label: "Recent Ingestion Debug",
    method: "GET",
    path: "/logs/debug/recent",
    description: "Return the tenant-scoped golden debug stream with raw requests, processed logs, and ingestion errors.",
    pageHref: "/dashboard/monitoring/ingestion",
  },
  {
    category: "Logs",
    label: "Get Log",
    method: "GET",
    path: "/logs/{log_id}",
    description: "Retrieve canonical details for a specific log record.",
    pageHref: "/dashboard/logs",
  },
  {
    category: "Logs",
    label: "Verify Log Chain",
    method: "GET",
    path: "/logs/{log_id}/verify",
    description: "Run verification checks for an existing log record.",
    pageHref: "/dashboard/verify",
  },
  {
    category: "Logs",
    label: "Delete Log",
    method: "POST",
    path: "/logs/{log_id}/delete",
    description: "Soft delete a log while preserving the integrity trail.",
    pageHref: "/dashboard/logs",
  },
  {
    category: "Logs",
    label: "Export Proof",
    method: "GET",
    path: "/logs/export-proof?from={iso_from}&to={iso_to}",
    description: "Export a proof bundle for a time-bounded set of logs.",
    pageHref: "/dashboard/system/anchoring",
  },
  {
    category: "Batches",
    label: "Seal Batch API",
    method: "POST",
    path: "/batches/seal",
    description: "Seal the current open batch for downstream proof generation.",
    pageHref: "/dashboard/system/pipeline",
    samplePayload: '{\n  "batch_id": "batch_demo_1"\n}',
  },
  {
    category: "Batches",
    label: "List Batches",
    method: "GET",
    path: "/batches",
    description: "List recently created batches.",
    pageHref: "/dashboard/system/pipeline",
  },
  {
    category: "Batches",
    label: "Get Batch",
    method: "GET",
    path: "/batches/{batch_id}",
    description: "Return metadata for a specific batch.",
    pageHref: "/dashboard/system/pipeline",
  },
  {
    category: "Batches",
    label: "Batch Status",
    method: "GET",
    path: "/batches/{batch_id}/status",
    description: "Return current sealing and processing state for a batch.",
    pageHref: "/dashboard/system/pipeline",
  },
  {
    category: "Batches",
    label: "Finalize Batch",
    method: "POST",
    path: "/batches/{batch_id}/finalize",
    description: "Finalize a batch before anchoring or export.",
    pageHref: "/dashboard/system/pipeline",
    samplePayload: '{\n  "note": "Finalize this batch for export."\n}',
  },
  {
    category: "Batches",
    label: "Get Batch Proof Bundle",
    method: "GET",
    path: "/batches/{batch_id}/proof-bundle",
    description: "Return the proof bundle associated with a batch.",
    pageHref: "/dashboard/system/anchoring",
  },
  {
    category: "Anchoring",
    label: "Anchor Batch",
    method: "POST",
    path: "/batches/{batch_id}/anchor",
    description: "Anchor a finalized batch and emit an attestation record.",
    pageHref: "/dashboard/system/anchoring",
    samplePayload: '{\n  "network": "testnet"\n}',
  },
  {
    category: "Anchoring",
    label: "Get Anchor Proof",
    method: "GET",
    path: "/anchors/{batch_id}",
    description: "Return the anchor proof for a batch.",
    pageHref: "/dashboard/system/anchoring",
  },
  {
    category: "Verification",
    label: "Verify Batch API",
    method: "GET",
    path: "/verify/batch/{batch_id}",
    description: "Verify inclusion and integrity for an anchored batch.",
    pageHref: "/dashboard/monitoring/integrity",
  },
  {
    category: "Verification",
    label: "Verify Log Inclusion API",
    method: "GET",
    path: "/verify/log/{log_id}",
    description: "Resolve verification state for a specific log identifier.",
    pageHref: "/dashboard/verify",
  },
  {
    category: "Evidence",
    label: "Get Legal Evidence",
    method: "GET",
    path: "/evidence/batch/{batch_id}",
    description: "Generate or retrieve a legal evidence package for a batch.",
    pageHref: "/dashboard/system/anchoring",
  },
  {
    category: "Export",
    label: "Queue Export",
    method: "POST",
    path: "/exports/{batch_id}",
    description: "Queue an asynchronous export job for a batch artifact bundle.",
    pageHref: "/dashboard/system/anchoring",
  },
  {
    category: "Export",
    label: "Get Export Job",
    method: "GET",
    path: "/exports/{export_id}",
    description: "Inspect export job status and metadata.",
    pageHref: "/dashboard/system/anchoring",
  },
  {
    category: "Export",
    label: "Download Export",
    method: "GET",
    path: "/exports/{export_id}/download",
    description: "Download the generated export artifact.",
    pageHref: "/dashboard/system/anchoring",
  },
  {
    category: "Webhooks",
    label: "List Webhook Events",
    method: "GET",
    path: "/webhooks/events",
    description: "Inspect inbound webhook event deliveries and recent activity.",
    pageHref: "/dashboard/notifications",
    liveOnly: true,
  },
  {
    category: "Webhooks",
    label: "Register Webhook",
    method: "POST",
    path: "/webhooks",
    description: "Register a webhook target for downstream notifications.",
    pageHref: "/dashboard/notifications",
    samplePayload:
      '{\n  "url": "https://example.com/webhooks/blocklog",\n  "events": ["batch.sealed", "anchor.completed"]\n}',
    liveOnly: true,
  },
  {
    category: "AI Provenance",
    label: "Ingest Agentic Action",
    method: "POST",
    path: "/ai/actions",
    description: "Store an AI or agent action inside the audit trail.",
    pageHref: "/dashboard/playground",
    samplePayload:
      '{\n  "agent_id": "agent_42",\n  "action": "policy.review",\n  "payload": {\n    "model": "gpt-5.4",\n    "decision": "approved"\n  }\n}',
  },
  {
    category: "Human In The Loop",
    label: "Get Override Challenge",
    method: "GET",
    path: "/request-override/{log_id}",
    description: "Return the override challenge for a protected log action.",
    pageHref: "/dashboard/verify",
  },
  {
    category: "Human In The Loop",
    label: "Approve HITL",
    method: "POST",
    path: "/hitl/approve",
    description: "Approve a human-in-the-loop challenge or override.",
    pageHref: "/dashboard/verify",
    samplePayload:
      '{\n  "log_id": "log_10021",\n  "approver": "compliance.lead",\n  "decision": "approved"\n}',
  },
];

export const apiCategories = Array.from(new Set(apiCatalog.map((endpoint) => endpoint.category)));
